### ISSUE TITLE
Missing copyright in derived files

### ISSUE THREAD

**Issue by mguthaus** [asyncvlsi/AMC#10]
In the most recent commits, portions of the new unit tests are modified from OpenRAM yet the copyright has been removed. As a reminder, the copyright must be maintained "with or without modification".

**Comment by mguthaus** [comment]
As another example, commit 507f55304f127b677e9f42e1c0a4b5a1ce832d12 explicitly removes a copyright from a modified file.

**Comment by sataei** [comment]
I just added the copyright back. This happened due some inconsistency between my master and development branch. 
Thank you for pointing that out.

**Comment by mguthaus** [comment]
Ok, hopefully you will fix the unit tests as well. There are even cut & pasted typos that make it quite obvious it was directly used.

**Comment by sataei** [comment]
I deleted the most recent test units. We are going to change our testing framework in next major release and all other unit tests will also be replaced in next version.
