### ISSUE TITLE
Missing Copyright

### ISSUE THREAD

**Issue by mguthaus** [asyncvlsi/AMC#2]
This project was copied from OpenRAM, but the BSD license has not been followed. You are supposed to include the previous copyright. Please add this. Thanks!

**Comment by sataei** [comment]
We just added AMC license file (GNU GPL v2.0). Portions of code that are derived from OpenRAM and used in AMC with no/minor modification, will remain under BSD license.

**Comment by mguthaus** [comment]
Thank you.

---
Matthew Guthaus
Professor, Computer Science and Engineering
University of California Santa Cruz
https://www.soe.ucsc.edu/people/mrg
