### ISSUE TITLE
Missing shebang line in AMC.py

### ISSUE THREAD

**Issue by mguthaus** [asyncvlsi/AMC#7]
First lines in Unix scripts generally start with the interpreter or a line to get the interpreter from the current path. Usually this looks like this:
`#!/usr/bin/env python2
`
It is missing from AMC.py, so you cannot just type:
`./AMC.py`
but instead have to type:
`python2 AMC.py`

https://en.wikipedia.org/wiki/Shebang_(Unix)

**Comment by sataei** [comment]
Thank you. I added the shebang.
