### ISSUE TITLE
No .lib file generated

### ISSUE THREAD

**Issue by mguthaus** [asyncvlsi/AMC#8]
The output files are listed as:
 Output files are AMC_SRAM.(sp|gds|v|lib|lef)
However, there is no .lib file generated for use with synthesis.

**Comment by sataei** [comment]
.lib generation can be activated by setting the _characterizer_ in _options.py_. 
It is deactivated by default because the current characterization is slow and depends on Synopsys tools.

**Comment by mguthaus** [comment]
Ok, the above output is misleading and should probably be fixed then.

**Comment by sataei** [comment]
lib is removed from the list of AMC_SRAM output files. I added a comment in AMC.py on how to generate .lib file.
